### ISSUE TITLE
Java: Unsupported class file major version 57

### ISSUE THREAD

**Issue by miles-blaq** [exercism/support#73] opened 2019-10-04 07:52 UTC
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/milesblaq/Exercism/java/hello-world/build.gradle'

* What went wrong:
Could not compile build file '/Users/milesblaq/Exercism/java/hello-world/build.gradle'.
> startup failed:
  General error during semantic analysis: Unsupported class file major version 57
  
  java.lang.IllegalArgumentException: Unsupported class file major version 57
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:184)
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:166)
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:152)
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:273)
        at org.codehaus.groovy.ast.decompiled.AsmDecompiler.parseClass(AsmDecompiler.java:81)

**Comment by sshine** [comment] 2019-10-07 11:26
Now that the issue has been transferred away from exercism/exercism there is no longer any point in keeping it open for visibility. I will keep in mind that it is in this repo instead, in case others come along and report errors with Gradle and Java 13.

**Closed by sshine** 2019-10-07 11:26 UTC

**Comment by iHiD** [comment] 2019-10-07 13:49
Sorry :)

**Comment by sshine** [comment] 2019-10-07 14:26
No problem!

**Comment by murdho** [comment] 2019-10-09 20:46
I stumbled upon the same error when starting out with **Kotlin** exercises. 

Here is a solution that works with **Java 13** for Kotlin exercise(s) (at least on **macOS**):
```shell
# Execute these commands inside some Kotlin exercise directory.
# I tried them out in the hello-world exercise directory.

# Give permissions to use a script as executable.
chmod +x gradlew

# Download and set up gradle.
./gradlew

 # Run the tests.
./gradlew test
```
Maybe this is helpful for someone.

Cheers! ☀️

**Comment by ryanthara** [comment] 2019-10-16 18:16
I can reproduce the same issues in a maven context.

`Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M3:test (default-test) on project common: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M3:test failed: Unsupported class file major version 57
`

**Comment by antonmry** [comment] 2019-11-01 22:41
I had the same problem using Java 13 and the new switch expressions (preview feature): https://openjdk.java.net/jeps/325

Solved with:

1. Upgrading to java 13 with sdkman: `sdk install java 13.0.1-open' 
2. Upgrading to gradle 6 with sdkman: `sdk install gradle 6.0-rc-2`
3. Upgrading the gradle wrapper: `gradle wrapper`
4. Adding the following snippet to build.gradle:

```
tasks.withType(JavaCompile) {
    options.compilerArgs += "--enable-preview"
}

tasks.withType(Test) {
    jvmArgs += "--enable-preview"
}

tasks.withType(JavaExec) {
    jvmArgs += '--enable-preview'
}
```

5. Enabling preview features in the IDE: https://blog.jetbrains.com/idea/2019/07/support-for-java-13-preview-features-in-intellij-idea-2019-2/

**Comment by Fernal73** [comment] 2019-11-21 10:15
Had to switch over to jdk 11 on arch Linux to get grade to work. Any idea when grade 6 will be available on arch Linux? I'm assuming that supports java 13.

**Comment by antonmry** [comment] 2019-11-21 14:21
it's available with sdkman, it should work well in Arch Linux. Great tool.

**Comment by Fernal73** [comment] 2019-11-21 16:15
Yah! I don't think it's available on Arch Linux for Termux. I ought to have made that clear at the outset.

**Comment by aymkin** [comment] 2019-12-24 12:46
> At a low level, it means your version of Java is incompatible with the one with which Gradle was compiled. If you're using Java 13, you could try and install and set as default Java 12, or [upgrade Gradle](https://gradle.org/install/) (although I don't know if it's available for Java 13).

In my case updating Gradle Plugin helped to solve that kind of error

**Comment by Farhankhalid33100** [comment] 2020-03-04 19:00
I had same issue but i resolved this by installing the older JDK version . i downloaded this from this link 
https://adoptopenjdk.net/?variant=openjdk8&jvmVariant=hotspot

**Comment by GaldinoJr** [comment] 2020-03-25 15:35
> At a low level it means your version of Java is incompatible with the one with which Gradle was compiled. If you're using Java 13, you could try and install and set as default Java 12, or [upgrade Gradle](https://gradle.org/install/) (although I don't know if it's available for Java 13).
> 
> However, the Java mentors may be able to give better advice, since I imagine that these errors tend to come with new releases of Java. For example, Java 13 was released in September 2019, so many packages haven't had time to push new binary releases yet.

I Tried to update Gradle version to 6.3 (the last until moment) but it`s not worked. I Changed my Java Version of 13 to 11 and it worked. Thanks for your help!!

**Comment by bernard01** [comment] 2020-04-04 12:11
This looks like a fundamental flaw to me. Software needs to be upgraded on every time a minor platform upgrade? I have never experienced anything like this. It stinks.

**Comment by sliatecinos** [comment] 2020-04-20 23:30
> ok thanks, that was the problem... i have replace jdk13 with jdk11 and it works well

Awesome! It worked for me!

**Comment by AJESH-CR** [comment] 2021-01-18 12:51
I'm also facing similar issue while using
- Java version: 13.0.2, vendor: Oracle Corporation
- Apache Maven 3.6.3
- Spring boot 2.1.9.RELEASE
- OS name: "windows 10", version: "10.0"

### Error message
```
exception is java.lang.IllegalArgumentException: Unsupported class file major version 57
```

Thanks

**Comment by boya678** [comment] 2021-01-25 22:29
there is a image on docker hub with the proble solved, tevolvers/sonarqube:7.9

**Comment by shishupaltech** [comment] 2021-09-10 07:03
Unsupported class file major version 57
how to resolve it please tell me.

**Comment by ASemeniuk** [comment] 2021-09-28 13:52
@shishupaltech I fixed it by going to `/android/gradle/gradle-wrapper.properties` and increasing version in `distributionUrl` (gradle-6.3-all.zip in my case)

**Comment by thatgriffith** [comment] 2021-11-02 05:58
> @shishupaltech I fixed it by going to `/android/gradle/gradle-wrapper.properties` and increasing version in `distributionUrl` (gradle-6.3-all.zip in my case)

This solved it for me! Huge thanks!

Gradle 6.3 even supports Java 14. Check this link for a compatibility matrix: https://docs.gradle.org/current/userguide/compatibility.html
